name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy repository
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
        with:
          source: '.'
          target: '/var/www/fastype/server'
      - name: Execute remote command
        uses: appleboy/ssh-action@master
        with:
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          host: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd /var/www/fastype/server
            npm i
            cd /var/www/fastype
            pm2 start ecosystem.config.js
